name: C/C++ CI

on:
  push:
    branches: 
      ["main"]
  pull_request:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with submodules recursively
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..

    - name: make
      run: | 
        make -C build
        
    - name: run tests
      run: |
        cd build
        ctest
