name: build_pipeline

on:
  workflow_dispatch:
    inputs:
      branchInput:
        description: 'Remote branch to validate'
        required: true

      branchOutput:
        description: 'Remote branch to push to'
        required: true

jobs:
  Start_Pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code with submodules recursively
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Build
      run: | 
        make -C build

    - name: Run Unit tests
      run: |
        cd build
        ctest -R CompilerTests
        
    - name: Initiate History_Sanitizer
      env:
        GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no'
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git config --global user.email "explodefromdelhi@github.com"
        git config --global user.name "byteman-spec"
        git switch -c ${{ github.event.inputs.branchInput }}
        git pull origin ${{ github.event.inputs.branchInput }} 
        git diff origin/main | grep -E "^\+\+\+ b|^[+-]#{1,2} [0-9]" > ind/sanitizer/git_diff.txt 

    - name: Run Sanitizer
      run: |
        ctest -R build/CompilerTests

  history_validator:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code with submodules recursively
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run History Validator
      env:
        GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no'
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git config --global user.email "explodefromdelhi@github.com"
        git config --global user.name "byteman-spec"
        git switch -c ${{ github.event.inputs.branchInput }}
        git pull origin ${{ github.event.inputs.branchInput }} 
        cd ind/sanitizer
        git diff origin/main | grep -E "^\+\+\+ b|^[+-]#{1,2} [0-9]" > git_diff.txt 
        pwd
        cd ../
        pwd
        cd ../
        pwd
        ctest -R SanitizerTests
  
        

# This job will run only if the previous jobs fail
 # This job will run only if the previous jobs fail
  stop_push:
    runs-on: ubuntu-latest
    needs: build_run_test
    if: failure()
    steps:
    - name: Stop Push and Show Error
      run: exit 1

  keep_push:
    runs-on: ubuntu-latest
    needs: build_run_test
    permissions:
      contents: write
    if: success()

    steps:
    - name: Checkout code with submodules recursively
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Push to input repository
      env:
        GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no'
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git config --global user.email "explodefromdelhi@github.com"
        git config --global user.name "byteman-spec"
        git switch -c ${{ github.event.inputs.branchInput }}
        git pull origin ${{ github.event.inputs.branchInput }} 
        git switch -c ${{ github.event.inputs.branchOutput }}
        git push -f origin ${{ github.event.inputs.branchOutput }}
        

