name: C/C++ CI

on:
  push:
    branches: 
      ["main" , "FailingPipelinecheck"]
  pull_request:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with submodules recursively
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..

    - name: make
      run: | 
        make -C build
        
    - name: run tests
      run: |
        cd build
        ctest


# This job will run only if the previous jobs fail
 # This job will run only if the previous jobs fail
  stop_push:
    runs-on: ubuntu-latest
    needs: build
    if: failure()

    steps:
    - name: Stop Push and Show Error
      run: exit 1
