name: C/C++ CI

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Remote branch to push to'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with submodules recursively
      uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..

    - name: make
      run: | 
        make -C build
        
    - name: run tests
      run: |
        cd build
        ctest


# This job will run only if the previous jobs fail
 # This job will run only if the previous jobs fail
  stop_push:
    runs-on: ubuntu-latest
    needs: build
    if: failure()
    steps:
    - name: Stop Push and Show Error
      run: exit 1

  keep_push:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
    - name: Checkout code with submodules recursively
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Push to input repository
      run: |
        git config --global user.email "explodefromdelhi@github.com"
        git config --global user.name "byteman-spec"
        git add .
        git commit -m "[b-spec_actions]pushing code to remote repository"
        git push -u origin ${{ github.event.inputs.branch }}
    env:
        GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no'
    
